/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mitochondria.glb --transform
Author: Vida Systems (https://sketchfab.com/objects1)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/mitochondria-cell-organelles-397631a85faa487ba1f1cc4fe5e1b7e3
Title: Mitochondria - Cell Organelles
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mitochondria(props) {
  const { nodes, materials } = useGLTF('/mitochondria-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.matrix_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-66.59, -17.75, -7.42]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.granule_0001_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[19.64, -4.33, -5]} rotation={[-Math.PI / 2, 0, 0]} scale={6.96} />
      <mesh geometry={nodes.granule_0002_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[23.95, -4.33, -22.54]} rotation={[-0.78, 0.08, -1.7]} scale={6.96} />
      <mesh geometry={nodes.granule_0003_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-12.5, -4.33, -12.26]} rotation={[-2.66, -0.95, 1.82]} scale={6.96} />
      <mesh geometry={nodes.granule_0004_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-8.04, -4.33, 16.36]} rotation={[-1.02, -0.46, -1.73]} scale={6.96} />
      <mesh geometry={nodes.granule_0005_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-37.18, -4.33, 25.53]} rotation={[1.52, -0.46, -1.73]} scale={6.96} />
      <mesh geometry={nodes.granule_0006_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-47.68, -4.33, -15.72]} rotation={[-1.46, -1.12, 1.53]} scale={6.96} />
      <mesh geometry={nodes.granule_0000_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-63.31, -4.33, 8.83]} rotation={[-Math.PI / 2, 0, 0]} scale={6.96} />
      <mesh geometry={nodes.dna_03_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[4.56, -3.69, 2.42]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.dna_02_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-31.43, -4.79, 4.32]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.dna_01_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-71.91, -4.24, 9.91]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.shell_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.cristae_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/mitochondria-transformed.glb')
