/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --transform cosmic_cell.glb
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosmic-cell-9dffefa4bee348879d1d7b539965dbc5
Title: Cosmic Cell
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Nucleus(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cosmic_cell-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="05_0" />
              <group name="Sphere002_1" position={[4.94, -0.06, 0]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.material} />
              </group>
              <group name="13_2" rotation={[Math.PI, 0, Math.PI]} />
              <group name="Sphere001_3" position={[-4.94, 0.06, 0]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material} />
              </group>
              <group name="01_4" rotation={[0, Math.PI / 2, 0]} />
              <group name="Sphere003_5" position={[0, 0, -4.94]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.material} />
              </group>
              <group name="09_6" rotation={[0, -1.57, 0]} />
              <group name="Sphere004_7" position={[0, 0, 4.94]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material} />
              </group>
              <group name="03_8" rotation={[0, Math.PI / 4, 0]} />
              <group name="Sphere005_9" position={[3.49, -0.04, -3.49]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.material} />
              </group>
              <group name="11_10" rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
              <group name="Sphere006_11" position={[-3.49, 0.04, 3.49]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material} />
              </group>
              <group name="15_12" rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
              <group name="Sphere007_13" position={[-3.49, 0.04, -3.49]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.material} />
              </group>
              <group name="07_14" rotation={[0, -Math.PI / 4, 0]} />
              <group name="Sphere008_15" position={[3.49, -0.04, 3.49]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material} />
              </group>
              <group name="04_16" rotation={[0, 0.39, 0]} />
              <group name="Sphere009_17" position={[4.57, -0.05, -1.89]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.material} />
              </group>
              <group name="12_18" rotation={[Math.PI, -0.39, Math.PI]} />
              <group name="Sphere010_19" position={[-4.57, 0.05, 1.89]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material} />
              </group>
              <group name="16_20" rotation={[-Math.PI, 1.18, -Math.PI]} />
              <group name="Sphere011_21" position={[-1.89, 0.02, -4.57]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.material} />
              </group>
              <group name="08_22" rotation={[0, -1.18, 0]} />
              <group name="Sphere012_23" position={[1.89, -0.02, 4.57]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material} />
              </group>
              <group name="02_24" rotation={[0, 1.18, 0]} />
              <group name="Sphere013_25" position={[1.89, -0.02, -4.56]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.material} />
              </group>
              <group name="10_26" rotation={[Math.PI, -1.18, Math.PI]} />
              <group name="Sphere014_27" position={[-1.89, 0.02, 4.56]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.material} />
              </group>
              <group name="14_28" rotation={[-Math.PI, 0.39, -Math.PI]} />
              <group name="Sphere015_29" position={[-4.56, 0.05, -1.89]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.material} />
              </group>
              <group name="06_30" rotation={[0, -0.39, 0]} />
              <group name="Sphere016_31" position={[4.56, -0.05, 1.89]} rotation={[0, 0, Math.PI]} scale={0.98}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material} />
              </group>
              <group name="05001_32" position={[0.02, 1.69, 0]} rotation={[0, -0.19, 0]} scale={0.9} />
              <group name="Sphere017_33" position={[4.38, 1.64, 0.86]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.material} />
              </group>
              <group name="13001_34" position={[0.02, 1.69, 0]} rotation={[-Math.PI, 0.19, -Math.PI]} scale={0.9} />
              <group name="Sphere018_35" position={[-4.34, 1.74, -0.86]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material} />
              </group>
              <group name="01001_36" position={[0.02, 1.69, 0]} rotation={[0, 1.38, 0]} scale={0.9} />
              <group name="Sphere019_37" position={[0.88, 1.68, -4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.material} />
              </group>
              <group name="09001_38" position={[0.02, 1.69, 0]} rotation={[Math.PI, -1.38, Math.PI]} scale={0.9} />
              <group name="Sphere020_39" position={[-0.84, 1.7, 4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material} />
              </group>
              <group name="03001_40" position={[0.02, 1.69, 0]} rotation={[0, 0.59, 0]} scale={0.9} />
              <group name="Sphere021_41" position={[3.71, 1.65, -2.48]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.material} />
              </group>
              <group name="11001_42" position={[0.02, 1.69, 0]} rotation={[Math.PI, -0.59, Math.PI]} scale={0.9} />
              <group name="Sphere022_43" position={[-3.67, 1.74, 2.48]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material} />
              </group>
              <group name="15001_44" position={[0.02, 1.69, 0]} rotation={[-Math.PI, 0.98, -Math.PI]} scale={0.9} />
              <group name="Sphere023_45" position={[-2.46, 1.72, -3.69]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.material} />
              </group>
              <group name="07001_46" position={[0.02, 1.69, 0]} rotation={[0, -0.98, 0]} scale={0.9} />
              <group name="Sphere024_47" position={[2.5, 1.67, 3.69]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material} />
              </group>
              <group name="04001_48" position={[0.02, 1.69, 0]} rotation={[0, 0.2, 0]} scale={0.9} />
              <group name="Sphere025_49" position={[4.38, 1.64, -0.87]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.material} />
              </group>
              <group name="12001_50" position={[0.02, 1.69, 0]} rotation={[Math.PI, -0.2, Math.PI]} scale={0.9} />
              <group name="Sphere026_51" position={[-4.34, 1.74, 0.87]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material} />
              </group>
              <group name="16001_52" position={[0.02, 1.69, 0]} rotation={[-Math.PI, 1.37, -Math.PI]} scale={0.9} />
              <group name="Sphere027_53" position={[-0.85, 1.7, -4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.material} />
              </group>
              <group name="08001_54" position={[0.02, 1.69, 0]} rotation={[0, -1.37, 0]} scale={0.9} />
              <group name="Sphere028_55" position={[0.89, 1.68, 4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.material} />
              </group>
              <group name="02001_56" position={[0.02, 1.69, 0]} rotation={[0, 0.98, 0]} scale={0.9} />
              <group name="Sphere029_57" position={[2.48, 1.67, -3.7]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.material} />
              </group>
              <group name="10001_58" position={[0.02, 1.69, 0]} rotation={[Math.PI, -0.98, Math.PI]} scale={0.9} />
              <group name="Sphere030_59" position={[-2.45, 1.72, 3.7]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.material} />
              </group>
              <group name="14001_60" position={[0.02, 1.69, 0]} rotation={[-Math.PI, 0.59, -Math.PI]} scale={0.9} />
              <group name="Sphere031_61" position={[-3.68, 1.74, -2.47]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.material} />
              </group>
              <group name="06003_62" position={[0.02, 1.69, 0]} rotation={[0, -0.59, 0]} scale={0.9} />
              <group name="Sphere032_63" position={[3.72, 1.65, 2.47]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material} />
              </group>
              <group name="05002_64" position={[0.04, 3.07, 0]} scale={0.76} />
              <group name="Sphere033_65" position={[3.77, 3.03, 0]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.material} />
              </group>
              <group name="13002_66" position={[0.04, 3.07, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.76} />
              <group name="Sphere034_67" position={[-3.7, 3.12, 0]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material} />
              </group>
              <group name="01002_68" position={[0.04, 3.07, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.76} />
              <group name="Sphere035_69" position={[0.04, 3.07, -3.73]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.material} />
              </group>
              <group name="09002_70" position={[0.04, 3.07, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.76} />
              <group name="Sphere036_71" position={[0.04, 3.07, 3.73]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.material} />
              </group>
              <group name="03002_72" position={[0.04, 3.07, 0]} rotation={[0, Math.PI / 4, 0]} scale={0.76} />
              <group name="Sphere037_73" position={[2.67, 3.04, -2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.material} />
              </group>
              <group name="11002_74" position={[0.04, 3.07, 0]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.76} />
              <group name="Sphere038_75" position={[-2.6, 3.1, 2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material} />
              </group>
              <group name="15002_76" position={[0.04, 3.07, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.76} />
              <group name="Sphere039_77" position={[-2.6, 3.1, -2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.material} />
              </group>
              <group name="07002_78" position={[0.04, 3.07, 0]} rotation={[0, -Math.PI / 4, 0]} scale={0.76} />
              <group name="Sphere040_79" position={[2.67, 3.04, 2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material} />
              </group>
              <group name="04002_80" position={[0.04, 3.07, 0]} rotation={[0, 0.39, 0]} scale={0.76} />
              <group name="Sphere041_81" position={[3.48, 3.03, -1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.material} />
              </group>
              <group name="12002_82" position={[0.04, 3.07, 0]} rotation={[Math.PI, -0.39, Math.PI]} scale={0.76} />
              <group name="Sphere042_83" position={[-3.41, 3.11, 1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.material} />
              </group>
              <group name="16002_84" position={[0.04, 3.07, 0]} rotation={[-Math.PI, 1.18, -Math.PI]} scale={0.76} />
              <group name="Sphere043_85" position={[-1.39, 3.09, -3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.material} />
              </group>
              <group name="08002_86" position={[0.04, 3.07, 0]} rotation={[0, -1.18, 0]} scale={0.76} />
              <group name="Sphere044_87" position={[1.46, 3.06, 3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.material} />
              </group>
              <group name="02002_88" position={[0.04, 3.07, 0]} rotation={[0, 1.18, 0]} scale={0.76} />
              <group name="Sphere045_89" position={[1.47, 3.06, -3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.material} />
              </group>
              <group name="10002_90" position={[0.04, 3.07, 0]} rotation={[Math.PI, -1.18, Math.PI]} scale={0.76} />
              <group name="Sphere046_91" position={[-1.4, 3.09, 3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material} />
              </group>
              <group name="14002_92" position={[0.04, 3.07, 0]} rotation={[-Math.PI, 0.39, -Math.PI]} scale={0.76} />
              <group name="Sphere047_93" position={[-3.41, 3.11, -1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.material} />
              </group>
              <group name="06005_94" position={[0.04, 3.07, 0]} rotation={[0, -0.39, 0]} scale={0.76} />
              <group name="Sphere048_95" position={[3.48, 3.03, 1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.material} />
              </group>
              <group name="05003_96" position={[0.05, 4.04, 0]} rotation={[0, -0.19, 0]} scale={0.62} />
              <group name="Sphere049_97" position={[3.03, 4, 0.59]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.material} />
              </group>
              <group name="13003_98" position={[0.05, 4.04, 0]} rotation={[-Math.PI, 0.19, -Math.PI]} scale={0.62} />
              <group name="Sphere050_99" position={[-2.94, 4.07, -0.59]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.material} />
              </group>
              <group name="01003_100" position={[0.05, 4.04, 0]} rotation={[0, 1.38, 0]} scale={0.62} />
              <group name="Sphere051_101" position={[0.63, 4.03, -2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.material} />
              </group>
              <group name="09003_102" position={[0.05, 4.04, 0]} rotation={[Math.PI, -1.38, Math.PI]} scale={0.62} />
              <group name="Sphere052_103" position={[-0.54, 4.05, 2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.material} />
              </group>
              <group name="03003_104" position={[0.05, 4.04, 0]} rotation={[0, 0.59, 0]} scale={0.62} />
              <group name="Sphere053_105" position={[2.57, 4.01, -1.7]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.material} />
              </group>
              <group name="11003_106" position={[0.05, 4.04, 0]} rotation={[Math.PI, -0.59, Math.PI]} scale={0.62} />
              <group name="Sphere054_107" position={[-2.48, 4.07, 1.7]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.material} />
              </group>
              <group name="15003_108" position={[0.05, 4.04, 0]} rotation={[-Math.PI, 0.98, -Math.PI]} scale={0.62} />
              <group name="Sphere055_109" position={[-1.65, 4.06, -2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.material} />
              </group>
              <group name="07003_110" position={[0.05, 4.04, 0]} rotation={[0, -0.98, 0]} scale={0.62} />
              <group name="Sphere056_111" position={[1.74, 4.02, 2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.material} />
              </group>
              <group name="04003_112" position={[0.05, 4.04, 0]} rotation={[0, 0.2, 0]} scale={0.62} />
              <group name="Sphere057_113" position={[3.03, 4, -0.6]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials.material} />
              </group>
              <group name="12003_114" position={[0.05, 4.04, 0]} rotation={[Math.PI, -0.2, Math.PI]} scale={0.62} />
              <group name="Sphere058_115" position={[-2.94, 4.07, 0.6]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.material} />
              </group>
              <group name="16003_116" position={[0.05, 4.04, 0]} rotation={[-Math.PI, 1.37, -Math.PI]} scale={0.62} />
              <group name="Sphere059_117" position={[-0.55, 4.05, -2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials.material} />
              </group>
              <group name="08003_118" position={[0.05, 4.04, 0]} rotation={[0, -1.37, 0]} scale={0.62} />
              <group name="Sphere060_119" position={[0.64, 4.03, 2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.material} />
              </group>
              <group name="02003_120" position={[0.05, 4.04, 0]} rotation={[0, 0.98, 0]} scale={0.62} />
              <group name="Sphere061_121" position={[1.73, 4.02, -2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials.material} />
              </group>
              <group name="10003_122" position={[0.05, 4.04, 0]} rotation={[Math.PI, -0.98, Math.PI]} scale={0.62} />
              <group name="Sphere062_123" position={[-1.64, 4.06, 2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.material} />
              </group>
              <group name="14003_124" position={[0.05, 4.04, 0]} rotation={[-Math.PI, 0.59, -Math.PI]} scale={0.62} />
              <group name="Sphere063_125" position={[-2.49, 4.07, -1.69]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_191" geometry={nodes.Object_191.geometry} material={materials.material} />
              </group>
              <group name="06007_126" position={[0.05, 4.04, 0]} rotation={[0, -0.59, 0]} scale={0.62} />
              <group name="Sphere064_127" position={[2.58, 4.01, 1.69]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.material} />
              </group>
              <group name="05004_128" position={[0.05, 4.7, 0]} rotation={[0, 0.73, 0]} scale={0.5} />
              <group name="Sphere065_129" position={[1.89, 4.68, -1.65]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_197" geometry={nodes.Object_197.geometry} material={materials.material} />
              </group>
              <group name="13004_130" position={[0.05, 4.7, 0]} rotation={[Math.PI, -0.73, Math.PI]} scale={0.5} />
              <group name="Sphere066_131" position={[-1.78, 4.72, 1.65]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.material} />
              </group>
              <group name="01004_132" position={[0.05, 4.7, 0]} rotation={[-Math.PI, 0.84, -Math.PI]} scale={0.5} />
              <group name="Sphere067_133" position={[-1.6, 4.72, -1.84]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_203" geometry={nodes.Object_203.geometry} material={materials.material} />
              </group>
              <group name="09004_134" position={[0.05, 4.7, 0]} rotation={[0, -0.84, 0]} scale={0.5} />
              <group name="Sphere068_135" position={[1.71, 4.68, 1.84]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.material} />
              </group>
              <group name="03004_136" position={[0.05, 4.7, 0]} rotation={[0, 1.52, 0]} scale={0.5} />
              <group name="Sphere069_137" position={[0.18, 4.69, -2.47]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials.material} />
              </group>
              <group name="11004_138" position={[0.05, 4.7, 0]} rotation={[Math.PI, -1.52, Math.PI]} scale={0.5} />
              <group name="Sphere070_139" position={[-0.07, 4.7, 2.47]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.material} />
              </group>
              <group name="15004_140" position={[0.05, 4.7, 0]} rotation={[-Math.PI, 0.05, -Math.PI]} scale={0.5} />
              <group name="Sphere071_141" position={[-2.41, 4.72, -0.13]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.material} />
              </group>
              <group name="07004_142" position={[0.05, 4.7, 0]} rotation={[0, -0.05, 0]} scale={0.5} />
              <group name="Sphere072_143" position={[2.52, 4.67, 0.13]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials.material} />
              </group>
              <group name="04004_144" position={[0.05, 4.7, 0]} rotation={[0, 1.13, 0]} scale={0.5} />
              <group name="Sphere073_145" position={[1.12, 4.68, -2.23]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.material} />
              </group>
              <group name="12004_146" position={[0.05, 4.7, 0]} rotation={[Math.PI, -1.13, Math.PI]} scale={0.5} />
              <group name="Sphere074_147" position={[-1.01, 4.71, 2.23]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.material} />
              </group>
              <group name="16004_148" position={[0.05, 4.7, 0]} rotation={[-Math.PI, 0.45, -Math.PI]} scale={0.5} />
              <group name="Sphere075_149" position={[-2.18, 4.72, -1.06]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.material} />
              </group>
              <group name="08004_150" position={[0.05, 4.7, 0]} rotation={[0, -0.45, 0]} scale={0.5} />
              <group name="Sphere076_151" position={[2.28, 4.67, 1.06]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials.material} />
              </group>
              <group name="02004_152" position={[0.05, 4.7, 0]} rotation={[-Math.PI, 1.23, -Math.PI]} scale={0.5} />
              <group name="Sphere077_153" position={[-0.77, 4.71, -2.33]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials.material} />
              </group>
              <group name="10004_154" position={[0.05, 4.7, 0]} rotation={[0, -1.23, 0]} scale={0.5} />
              <group name="Sphere078_155" position={[0.88, 4.69, 2.33]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.material} />
              </group>
              <group name="14004_156" position={[0.05, 4.7, 0]} rotation={[Math.PI, -0.34, Math.PI]} scale={0.5} />
              <group name="Sphere079_157" position={[-2.28, 4.72, 0.82]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_239" geometry={nodes.Object_239.geometry} material={materials.material} />
              </group>
              <group name="06009_158" position={[0.05, 4.7, 0]} rotation={[0, 0.34, 0]} scale={0.5} />
              <group name="Sphere080_159" position={[2.38, 4.67, -0.82]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.material} />
              </group>
              <group name="05005_160" position={[-0.02, -1.69, 0]} rotation={[0, -0.19, 0]} scale={0.9} />
              <group name="Sphere081_161" position={[4.34, -1.74, 0.86]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_245" geometry={nodes.Object_245.geometry} material={materials.material} />
              </group>
              <group name="13005_162" position={[-0.02, -1.69, 0]} rotation={[-Math.PI, 0.19, -Math.PI]} scale={0.9} />
              <group name="Sphere082_163" position={[-4.38, -1.64, -0.86]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.material} />
              </group>
              <group name="01005_164" position={[-0.02, -1.69, 0]} rotation={[0, 1.38, 0]} scale={0.9} />
              <group name="Sphere083_165" position={[0.84, -1.7, -4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_251" geometry={nodes.Object_251.geometry} material={materials.material} />
              </group>
              <group name="09005_166" position={[-0.02, -1.69, 0]} rotation={[Math.PI, -1.38, Math.PI]} scale={0.9} />
              <group name="Sphere084_167" position={[-0.88, -1.68, 4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.material} />
              </group>
              <group name="03005_168" position={[-0.02, -1.69, 0]} rotation={[0, 0.59, 0]} scale={0.9} />
              <group name="Sphere085_169" position={[3.67, -1.74, -2.48]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials.material} />
              </group>
              <group name="11005_170" position={[-0.02, -1.69, 0]} rotation={[Math.PI, -0.59, Math.PI]} scale={0.9} />
              <group name="Sphere086_171" position={[-3.71, -1.65, 2.48]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.material} />
              </group>
              <group name="15005_172" position={[-0.02, -1.69, 0]} rotation={[-Math.PI, 0.98, -Math.PI]} scale={0.9} />
              <group name="Sphere087_173" position={[-2.5, -1.67, -3.69]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_263" geometry={nodes.Object_263.geometry} material={materials.material} />
              </group>
              <group name="07005_174" position={[-0.02, -1.69, 0]} rotation={[0, -0.98, 0]} scale={0.9} />
              <group name="Sphere088_175" position={[2.46, -1.72, 3.69]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.material} />
              </group>
              <group name="04005_176" position={[-0.02, -1.69, 0]} rotation={[0, 0.2, 0]} scale={0.9} />
              <group name="Sphere089_177" position={[4.34, -1.74, -0.87]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_269" geometry={nodes.Object_269.geometry} material={materials.material} />
              </group>
              <group name="12005_178" position={[-0.02, -1.69, 0]} rotation={[Math.PI, -0.2, Math.PI]} scale={0.9} />
              <group name="Sphere090_179" position={[-4.38, -1.64, 0.87]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.material} />
              </group>
              <group name="16005_180" position={[-0.02, -1.69, 0]} rotation={[-Math.PI, 1.37, -Math.PI]} scale={0.9} />
              <group name="Sphere091_181" position={[-0.89, -1.68, -4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_275" geometry={nodes.Object_275.geometry} material={materials.material} />
              </group>
              <group name="08005_182" position={[-0.02, -1.69, 0]} rotation={[0, -1.37, 0]} scale={0.9} />
              <group name="Sphere092_183" position={[0.85, -1.7, 4.36]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.material} />
              </group>
              <group name="02005_184" position={[-0.02, -1.69, 0]} rotation={[0, 0.98, 0]} scale={0.9} />
              <group name="Sphere093_185" position={[2.45, -1.72, -3.7]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.material} />
              </group>
              <group name="10005_186" position={[-0.02, -1.69, 0]} rotation={[Math.PI, -0.98, Math.PI]} scale={0.9} />
              <group name="Sphere094_187" position={[-2.48, -1.67, 3.7]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.material} />
              </group>
              <group name="14005_188" position={[-0.02, -1.69, 0]} rotation={[-Math.PI, 0.59, -Math.PI]} scale={0.9} />
              <group name="Sphere095_189" position={[-3.72, -1.65, -2.47]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_287" geometry={nodes.Object_287.geometry} material={materials.material} />
              </group>
              <group name="06011_190" position={[-0.02, -1.69, 0]} rotation={[0, -0.59, 0]} scale={0.9} />
              <group name="Sphere096_191" position={[3.68, -1.74, 2.47]} rotation={[0, 0, Math.PI]} scale={0.88}>
                <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials.material} />
              </group>
              <group name="05006_192" position={[-0.03, -3.05, 0]} scale={0.76} />
              <group name="Sphere097_193" position={[3.7, -3.09, 0]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.material} />
              </group>
              <group name="13006_194" position={[-0.03, -3.05, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.76} />
              <group name="Sphere098_195" position={[-3.77, -3.01, 0]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials.material} />
              </group>
              <group name="01006_196" position={[-0.03, -3.05, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.76} />
              <group name="Sphere099_197" position={[-0.03, -3.05, -3.73]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.material} />
              </group>
              <group name="09006_198" position={[-0.03, -3.05, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.76} />
              <group name="Sphere100_199" position={[-0.03, -3.05, 3.73]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials.material} />
              </group>
              <group name="03006_200" position={[-0.03, -3.05, 0]} rotation={[0, Math.PI / 4, 0]} scale={0.76} />
              <group name="Sphere101_201" position={[2.6, -3.08, -2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_305" geometry={nodes.Object_305.geometry} material={materials.material} />
              </group>
              <group name="11006_202" position={[-0.03, -3.05, 0]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.76} />
              <group name="Sphere102_203" position={[-2.67, -3.02, 2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials.material} />
              </group>
              <group name="15006_204" position={[-0.03, -3.05, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.76} />
              <group name="Sphere103_205" position={[-2.67, -3.02, -2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_311" geometry={nodes.Object_311.geometry} material={materials.material} />
              </group>
              <group name="07006_206" position={[-0.03, -3.05, 0]} rotation={[0, -Math.PI / 4, 0]} scale={0.76} />
              <group name="Sphere104_207" position={[2.6, -3.08, 2.64]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials.material} />
              </group>
              <group name="04006_208" position={[-0.03, -3.05, 0]} rotation={[0, 0.39, 0]} scale={0.76} />
              <group name="Sphere105_209" position={[3.41, -3.09, -1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials.material} />
              </group>
              <group name="12006_210" position={[-0.03, -3.05, 0]} rotation={[Math.PI, -0.39, Math.PI]} scale={0.76} />
              <group name="Sphere106_211" position={[-3.48, -3.01, 1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials.material} />
              </group>
              <group name="16006_212" position={[-0.03, -3.05, 0]} rotation={[-Math.PI, 1.18, -Math.PI]} scale={0.76} />
              <group name="Sphere107_213" position={[-1.46, -3.03, -3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials.material} />
              </group>
              <group name="08006_214" position={[-0.03, -3.05, 0]} rotation={[0, -1.18, 0]} scale={0.76} />
              <group name="Sphere108_215" position={[1.39, -3.06, 3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials.material} />
              </group>
              <group name="02006_216" position={[-0.03, -3.05, 0]} rotation={[0, 1.18, 0]} scale={0.76} />
              <group name="Sphere109_217" position={[1.4, -3.06, -3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_329" geometry={nodes.Object_329.geometry} material={materials.material} />
              </group>
              <group name="10006_218" position={[-0.03, -3.05, 0]} rotation={[Math.PI, -1.18, Math.PI]} scale={0.76} />
              <group name="Sphere110_219" position={[-1.46, -3.03, 3.45]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials.material} />
              </group>
              <group name="14006_220" position={[-0.03, -3.05, 0]} rotation={[-Math.PI, 0.39, -Math.PI]} scale={0.76} />
              <group name="Sphere111_221" position={[-3.48, -3.01, -1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.material} />
              </group>
              <group name="06013_222" position={[-0.03, -3.05, 0]} rotation={[0, -0.39, 0]} scale={0.76} />
              <group name="Sphere112_223" position={[3.41, -3.09, 1.43]} rotation={[0, 0, Math.PI]} scale={0.74}>
                <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials.material} />
              </group>
              <group name="05007_224" position={[-0.05, -3.98, 0]} rotation={[0, -0.19, 0]} scale={0.62} />
              <group name="Sphere113_225" position={[2.94, -4.01, 0.59]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_341" geometry={nodes.Object_341.geometry} material={materials.material} />
              </group>
              <group name="13007_226" position={[-0.05, -3.98, 0]} rotation={[-Math.PI, 0.19, -Math.PI]} scale={0.62} />
              <group name="Sphere114_227" position={[-3.03, -3.94, -0.59]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials.material} />
              </group>
              <group name="01007_228" position={[-0.05, -3.98, 0]} rotation={[0, 1.38, 0]} scale={0.62} />
              <group name="Sphere115_229" position={[0.54, -3.98, -2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_347" geometry={nodes.Object_347.geometry} material={materials.material} />
              </group>
              <group name="09007_230" position={[-0.05, -3.98, 0]} rotation={[Math.PI, -1.38, Math.PI]} scale={0.62} />
              <group name="Sphere116_231" position={[-0.63, -3.97, 2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials.material} />
              </group>
              <group name="03007_232" position={[-0.05, -3.98, 0]} rotation={[0, 0.59, 0]} scale={0.62} />
              <group name="Sphere117_233" position={[2.48, -4.01, -1.7]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_353" geometry={nodes.Object_353.geometry} material={materials.material} />
              </group>
              <group name="11007_234" position={[-0.05, -3.98, 0]} rotation={[Math.PI, -0.59, Math.PI]} scale={0.62} />
              <group name="Sphere118_235" position={[-2.57, -3.95, 1.7]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials.material} />
              </group>
              <group name="15007_236" position={[-0.05, -3.98, 0]} rotation={[-Math.PI, 0.98, -Math.PI]} scale={0.62} />
              <group name="Sphere119_237" position={[-1.74, -3.96, -2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_359" geometry={nodes.Object_359.geometry} material={materials.material} />
              </group>
              <group name="07007_238" position={[-0.05, -3.98, 0]} rotation={[0, -0.98, 0]} scale={0.62} />
              <group name="Sphere120_239" position={[1.65, -4, 2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials.material} />
              </group>
              <group name="04007_240" position={[-0.05, -3.98, 0]} rotation={[0, 0.2, 0]} scale={0.62} />
              <group name="Sphere121_241" position={[2.94, -4.01, -0.6]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_365" geometry={nodes.Object_365.geometry} material={materials.material} />
              </group>
              <group name="12007_242" position={[-0.05, -3.98, 0]} rotation={[Math.PI, -0.2, Math.PI]} scale={0.62} />
              <group name="Sphere122_243" position={[-3.03, -3.94, 0.6]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials.material} />
              </group>
              <group name="16007_244" position={[-0.05, -3.98, 0]} rotation={[-Math.PI, 1.37, -Math.PI]} scale={0.62} />
              <group name="Sphere123_245" position={[-0.64, -3.97, -2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_371" geometry={nodes.Object_371.geometry} material={materials.material} />
              </group>
              <group name="08007_246" position={[-0.05, -3.98, 0]} rotation={[0, -1.37, 0]} scale={0.62} />
              <group name="Sphere124_247" position={[0.55, -3.99, 2.98]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials.material} />
              </group>
              <group name="02007_248" position={[-0.05, -3.98, 0]} rotation={[0, 0.98, 0]} scale={0.62} />
              <group name="Sphere125_249" position={[1.64, -4, -2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_377" geometry={nodes.Object_377.geometry} material={materials.material} />
              </group>
              <group name="10007_250" position={[-0.05, -3.98, 0]} rotation={[Math.PI, -0.98, Math.PI]} scale={0.62} />
              <group name="Sphere126_251" position={[-1.73, -3.96, 2.53]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials.material} />
              </group>
              <group name="14007_252" position={[-0.05, -3.98, 0]} rotation={[-Math.PI, 0.59, -Math.PI]} scale={0.62} />
              <group name="Sphere127_253" position={[-2.58, -3.95, -1.69]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_383" geometry={nodes.Object_383.geometry} material={materials.material} />
              </group>
              <group name="06015_254" position={[-0.05, -3.98, 0]} rotation={[0, -0.59, 0]} scale={0.62} />
              <group name="Sphere128_255" position={[2.49, -4.01, 1.69]} rotation={[0, 0, Math.PI]} scale={0.6}>
                <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials.material} />
              </group>
              <group name="05008_256" position={[-0.05, -4.68, 0]} scale={0.5} />
              <group name="Sphere129_257" position={[2.42, -4.7, 0]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_389" geometry={nodes.Object_389.geometry} material={materials.material} />
              </group>
              <group name="13008_258" position={[-0.05, -4.68, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.5} />
              <group name="Sphere130_259" position={[-2.52, -4.65, 0]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials.material} />
              </group>
              <group name="01008_260" position={[-0.05, -4.68, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.5} />
              <group name="Sphere131_261" position={[-0.05, -4.68, -2.47]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_395" geometry={nodes.Object_395.geometry} material={materials.material} />
              </group>
              <group name="09008_262" position={[-0.05, -4.68, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.5} />
              <group name="Sphere132_263" position={[-0.05, -4.68, 2.47]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials.material} />
              </group>
              <group name="03008_264" position={[-0.05, -4.68, 0]} rotation={[0, Math.PI / 4, 0]} scale={0.5} />
              <group name="Sphere133_265" position={[1.69, -4.7, -1.75]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_401" geometry={nodes.Object_401.geometry} material={materials.material} />
              </group>
              <group name="11008_266" position={[-0.05, -4.68, 0]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={0.5} />
              <group name="Sphere134_267" position={[-1.8, -4.66, 1.75]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials.material} />
              </group>
              <group name="15008_268" position={[-0.05, -4.68, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.5} />
              <group name="Sphere135_269" position={[-1.8, -4.66, -1.75]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_407" geometry={nodes.Object_407.geometry} material={materials.material} />
              </group>
              <group name="07008_270" position={[-0.05, -4.68, 0]} rotation={[0, -Math.PI / 4, 0]} scale={0.5} />
              <group name="Sphere136_271" position={[1.69, -4.7, 1.75]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials.material} />
              </group>
              <group name="04008_272" position={[-0.05, -4.68, 0]} rotation={[0, 0.39, 0]} scale={0.5} />
              <group name="Sphere137_273" position={[2.23, -4.7, -0.94]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_413" geometry={nodes.Object_413.geometry} material={materials.material} />
              </group>
              <group name="12008_274" position={[-0.05, -4.68, 0]} rotation={[Math.PI, -0.39, Math.PI]} scale={0.5} />
              <group name="Sphere138_275" position={[-2.34, -4.65, 0.94]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials.material} />
              </group>
              <group name="16008_276" position={[-0.05, -4.68, 0]} rotation={[-Math.PI, 1.18, -Math.PI]} scale={0.5} />
              <group name="Sphere139_277" position={[-1, -4.66, -2.28]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_419" geometry={nodes.Object_419.geometry} material={materials.material} />
              </group>
              <group name="08008_278" position={[-0.05, -4.68, 0]} rotation={[0, -1.18, 0]} scale={0.5} />
              <group name="Sphere140_279" position={[0.89, -4.69, 2.28]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials.material} />
              </group>
              <group name="02008_280" position={[-0.05, -4.68, 0]} rotation={[0, 1.18, 0]} scale={0.5} />
              <group name="Sphere141_281" position={[0.89, -4.69, -2.28]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_425" geometry={nodes.Object_425.geometry} material={materials.material} />
              </group>
              <group name="10008_282" position={[-0.05, -4.68, 0]} rotation={[Math.PI, -1.18, Math.PI]} scale={0.5} />
              <group name="Sphere142_283" position={[-1, -4.66, 2.28]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials.material} />
              </group>
              <group name="14008_284" position={[-0.05, -4.68, 0]} rotation={[-Math.PI, 0.39, -Math.PI]} scale={0.5} />
              <group name="Sphere143_285" position={[-2.34, -4.65, -0.95]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_431" geometry={nodes.Object_431.geometry} material={materials.material} />
              </group>
              <group name="06017_286" position={[-0.05, -4.68, 0]} rotation={[0, -0.39, 0]} scale={0.5} />
              <group name="Sphere144_287" position={[2.23, -4.7, 0.95]} rotation={[0, 0, Math.PI]} scale={0.49}>
                <mesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials.material} />
              </group>
              <group name="Sphere_288" rotation={[0, 0, -0.01]} scale={[3.5, 5.43, 3.5]}>
                <mesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials.material_1} />
              </group>
              <group name="Icosphere_289" rotation={[0.01, 0, -0.01]} scale={8.55}>
                <mesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials.hhhhhhh} />
              </group>
              <group name="06001_291" scale={[5.99, 5.98, 5.99]} />
              <group name="06002_293" position={[0.02, 1.69, 0]} scale={5.39} />
              <group name="06004_294" position={[0.04, 3.07, 0]} scale={4.52} />
              <group name="06006_295" position={[0.05, 4.04, 0]} scale={3.69} />
              <group name="06008_296" position={[0.05, 4.7, 0]} scale={2.99} />
              <group name="06010_297" position={[-0.02, -1.69, 0]} scale={5.39} />
              <group name="06012_298" position={[-0.03, -3.05, 0]} scale={4.52} />
              <group name="06014_299" position={[-0.05, -3.98, 0]} scale={3.69} />
              <group name="06016_300" position={[-0.05, -4.68, 0]} scale={2.99} />
              <group name="Sphere145_290" scale={3.52}>
                <mesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials.CRRRR} />
              </group>
              <group name="Cube_292" rotation={[0, 0.2, 0]} scale={8.2}>
                <mesh name="Object_443" geometry={nodes.Object_443.geometry} material={materials.hide} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cosmic_cell-transformed.glb')
