/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 --transform C:\Users\finnh\Desktop\code\cell-l\org-v2\public\endoplasmic_reticulum.glb
Author: MajoraMaster (https://sketchfab.com/MajoraMaster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/endoplasmic-reticulum-cd27ea87988348faa351ae2b7237e1d9
Title: Endoplasmic Reticulum
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ER(props) {
  const { nodes, materials } = useGLTF('/endoplasmic_reticulum-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, -Math.PI]} scale={[2.79, 1.24, 1]}>
          <mesh geometry={nodes['ER-material'].geometry} material={materials.material} />
          <mesh geometry={nodes['ribosomes-material'].geometry} material={materials.ribosomes} />
          <mesh geometry={nodes['ribosomes-material_1'].geometry} material={materials.ribosomes} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/endoplasmic_reticulum-transformed.glb')
