/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 C:\Users\finnh\Desktop\code\cell-l\org-v2\golgi_apparatuscomplex.glb --transform
Author: MajoraMaster (https://sketchfab.com/MajoraMaster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golgi-apparatuscomplex-f9a893dac37e43a487bc92e7f828db50
Title: Golgi Apparatus/Complex
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Golgi(props) {
  const { nodes, materials } = useGLTF('/golgi_apparatuscomplex-transformed.glb')
  return (
    <group  {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh  geometry={nodes['GA-material'].geometry} material={materials.material} position={[0.03, 0, 0]} />
        <mesh geometry={nodes['vesicles-material'].geometry} material={materials.vesicles} position={[-1.32, -0.61, 0.37]} scale={0.11} />
      </group>
    </group>
  )
}

useGLTF.preload('/golgi_apparatuscomplex-transformed.glb')
