/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lysosome.glb --transform
Author: MajoraMaster (https://sketchfab.com/MajoraMaster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lysosome-ac57a5cb72484600a9826d66c556d377
Title: Lysosome
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lysosome(props) {
  const { nodes, materials } = useGLTF('/lysosome-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Lysosomes-material'].geometry} material={materials.Lysosomes} position={[2.64, 0, 0]} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} position={[1.65, 0, 0]} scale={0.06} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} position={[2.44, 0, 0.98]} scale={0.06} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} position={[2.44, 0.67, 0.72]} scale={0.06} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_0} position={[3.26, 0.67, 0.33]} scale={0.06} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} position={[1.86, 0.14, -0.57]} scale={0.06} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_0} position={[2.29, -0.87, 0.4]} scale={0.06} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} position={[2.29, 0.91, 0.15]} scale={0.06} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} position={[3.11, 0.82, -0.25]} scale={0.06} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} position={[2.56, -0.94, -0.29]} scale={0.06} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} position={[2.56, -0.57, -0.8]} scale={0.06} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.material_0} position={[2.56, 0.29, -0.93]} scale={0.06} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.material_0} position={[2.32, 0.8, -0.45]} scale={0.06} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.material_0} position={[3.26, -0.14, 0.75]} scale={0.06} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.material_0} position={[3.48, -0.45, 0.16]} scale={0.06} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.material_0} position={[3.58, 0, -0.29]} scale={0.06} />
      </group>
    </group>
  )
}

useGLTF.preload('/lysosome-transformed.glb')
