/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ribosome.glb -T
Author: 3D_UTPL (https://sketchfab.com/3D_UTPL)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/ribosoma-c586d726ef6344699fcbb2589845026e
Title: Ribosoma
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ribosome(props) {
  const { nodes, materials } = useGLTF('/ribosome-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.3}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.11, 0]} rotation={[0.04, -0.05, 0.01]} scale={0.04}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.piezagrande1} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.piezapequena} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.cenefa} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.pina6} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.bolitas} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.bola_pina4} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.pina4} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.pina7} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.pina8} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.pina9} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.pina3} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.bolapina3} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.bolapina11} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.pina1} />
            <mesh geometry={nodes.Object_20.geometry} material={materials['13_-_Default']} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.bolapina2} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.bolapina5} />
            <mesh geometry={nodes.Object_23.geometry} material={materials['01_-_Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ribosome-transformed.glb')
